### ISSUE TITLE
Cannot validate argument on parameter 'Id'.

### ISSUE THREAD

**Issue by Craig-Goodspeed** [mwpreston/AsBuiltReport.Rubrik.CDM#7]
I am getting this error:

> New-AsBuiltReport : Cannot validate argument on parameter 'Id'. The argument is null or empty. Provide an argument
> that is not null or empty, and then try the command again.
> At line:1 char:1
> + New-AsBuiltReport -Report Rubrik.CDM -Target rubrik.unh.edu -Credenti ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport
> 

No report data is being created,

This is the last bit of text I see before the error:

> VERBOSE: [ 22:37:00:880 ] [ Document ] - Processing paragraph 'The following contains information a[..]'.

This is the command I am executing: `New-AsBuiltReport -Report Rubrik.CDM -Target rubrik.unh.edu -Credential (Import-CliXML -Path 'C:\Temp\AsBuiltReports\clustercreds.xml') -Format HTML -Orientation Portrait -OutputPath 'C:\Temp\AsBuiltReports' -ReportConfigPath 'C:\Temp\AsBuiltReports\UNH.json' -AsBuiltConfigPath 'C:\Temp\AsBuiltReports\AsBuiltReport.json'`

Contents of 'UNH.json':

> {
>     "Report": {
>         "Name": "Rubrik As Built Report",
>         "Version": "1.0",
>         "Status": "Released"
>     },
>     "Options": {
> 
>     },
>     "InfoLevel": {
>         "_comment_": "0 = Disabled, 1 = Summary, 2 = Informative, 3 = Detailed, 4 = Adv Detailed, 5 = Comprehensive",
>         "Cluster": 5,
>         "SLADomains": 5,
>         "ProtectedObjects": 5,
>         "SnapshotRetention": 5
>     },
>     "HealthCheck": {
>        
>     }
> }
> 

Contents of 'AsBuiltReport.json':

> {
>     "Email":  {
>                   "Port":  null,
>                   "Credentials":  null,
>                   "Server":  null,
>                   "To":  null,
>                   "From":  null,
>                   "UseSSL":  null,
>                   "Body":  null
>               },
>     "Company":  {
>                     "FullName":  "University of New Hampshire",
>                     "Contact":  "Craig Goodspeed",
>                     "Phone":  "(603)862-2283",
>                     "Email":  "Craig.Goodspeed@unh.edu",
>                     "ShortName":  "UNH",
>                     "Address":  "Durham, NH"
>                 },
>     "UserFolder":  {
>                        "Path":  "C:\\Temp\\AsBuiltReports"
>                    },
>     "Report":  {
>                    "Author":  "Craig Goodspeed"
>                }
> }
> 
>

**Comment by Craig-Goodspeed** [comment]
So I was scrolling through the file 'Invoke-AsBuiltReport.Rubrik.CDM.ps1' for all instances of the variable 'ID', which I only found four instances and I checked the "Processing sections" in the output of the script and the only section where I could find the variable 'ID' being used and didn't find the successful completed message for was for processing the SLA Domains.

I have to assume it has something to do with the names of my SLAs or the $SLADomain.id that it is pulling from my cluster....but those are guesses ;-)

**Comment by mwpreston** [comment]
I think this probably has something to do with some null checks which are missing.  I've seen it pop up on reports generated when there is no Hyper-V VMs to process, or no Nutanix VMs, etc...

I will try and shore up the code when I get back to work in a week.  I also need to implement some better logging so we can see exactly where the script is failing - thanks for pointing this out...

**Comment by Craig-Goodspeed** [comment]
That is correct, we are a VMware shop so there are no Hyper-V or Nutanix VMs to process.

Let me know if I can provide any other additional information or when you have and update I can test.

Craig

**Comment by mwpreston** [comment]
@Craig-Goodspeed - are you able to pull down the latest version of the dev branch and try again - if anything I've implemented a number of null checks as well as verbose logging...

**Comment by Craig-Goodspeed** [comment]
I am still getting the same error, but attached is the output to the console for troubleshooting
[AsBuiltReport-Error.txt](https://github.com/mwpreston/AsBuiltReport.Rubrik.CDM/files/4294809/AsBuiltReport-Error.txt)

**Comment by mwpreston** [comment]
Err - my bad - added code to the AsBuiltCore as well - can you pull down my verbose version of the AsBuiltReport.Core (git clone https://github.com/mwpreston/AsBuiltReport.Core.git), checkout mpreston-verbose (git checkout mpreston-verbose) and Import it into a new PS session(Import-Module <path_to_where_you_cloned>\AsBuiltReport.Core -Force)
Also import the dev branch of this repo...

Then on the New-AsBuiltReport cmdlet that you run just add the -Verbose switch to the end?

And then give me the output?  Thx

**Comment by Craig-Goodspeed** [comment]
I am attaching the output from the test you messaged me in the Rubrik Guardian forums
[AsBuiltReport_output.txt](https://github.com/mwpreston/AsBuiltReport.Rubrik.CDM/files/4427819/AsBuiltReport_output.txt)

Let me know if I can provide any further information

**Comment by mwpreston** [comment]
New dev version should resolve this if you don't mind pulling down and trying again @Craig-Goodspeed

**Comment by Craig-Goodspeed** [comment]
BOOM!  I now have an extremely comprehensive report of my entire Rubrik backup cluster!

These changes worked, I am reviewing the report now to see if I find any data missing or wonky.
